name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          distribution: temurin
          java-version: 25

      - name: Cache Maven packages
        uses: actions/cache@v4

        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build project
        run: mvn clean verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}